<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-question.php
	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => 'Jibu 1',
		'a_convert_to_c' => 'Badili Jibu hili kuwa Oni',
		'a_convert_to_c_on' => 'Badili Jibu hili kuwa Oni katika:',
		'a_convert_warn' => 'Tahadhari: Mabadiliko haya hayataweza kubatilishwa.',
		'a_convert_warn_cs' => 'Tahadhari: Mabadiliko haya hayataweza kubatilishwa na yatapelekea kuhamishwa kwa jibu\'majibu kuwa comment.',
		'a_notify_email' => 'Nitumie barua-pepe kwa anuani hii, endapo jibu langu litachaguliwa au kutolewa maoni:',
		'a_notify_label' => 'Nitumie barua-pepe endapo jibu langu litachaguliwa au kutolewa maoni',
		'a_notify_x_label' => 'Nitumie barua-pepe (^) endapo jibu langu litachaguliwa au kutolewa maoni',
		'a_waiting_your_approval' => 'Jibu hili linasubiri uthibitisho wako',
		'a_your_waiting_approval' => 'Jibu lako litatazamwa na kuthibitishwa hivi punde.',
		'add_answer_button' => 'Ongeza Jibu',
		'add_comment_button' => 'Ongeza Oni',
		'add_q_favorites' => 'Ongeza swali hili katika vipendeleo vyangu',
		'anon_name_label' => 'Jina la kuonesha (chagua-lako):',
		'answer_button' => 'jibu',
		'answer_limit' => 'Majibu mengi mno yamepokelewa - tafadhali jaribu baada baada ya saa moja',
		'answer_must_be_approved' => 'Akauti yako lazima ithibitishwe kabla hujaweza kujibu swali.',
		'answer_must_confirm' => 'Tafadhali ^5thibitisha anuani yako ya barua-pepe^6 ili kujibu swali hili.',
		'answer_must_login' => 'Tafadhali ^1ingia ndani^2 au ^3jisajili^4 ili kujibu swali hili.',
		'answer_q_popup' => 'Jibu hili Swali',
		'approve_a_popup' => 'Thibitisha hili jibu',
		'approve_button' => 'thibitisha',
		'approve_c_popup' => 'Thibitisha hili oni',
		'approve_q_popup' => 'Thibitisha hili swali',
		'ask_button' => 'Uliza Swali',
		'ask_follow_from_a' => 'Swali lako litaoanisha na jibu hili:',
		'ask_follow_title' => 'Uliza swali lifananalo',
		'ask_limit' => 'Maswali mengi zaidi yamepokelewa - tafadhali jaribu tena baada ya saa moja',
		'ask_must_be_approved' => 'Akaunti yako ni lazima ithibitishwe kabla ya kuuliza swali.',
		'ask_must_confirm' => 'Tafadhali ^5thibitisha anauani yako ya barua-pepe^6 ili kuuliza swali.',
		'ask_must_login' => 'Tafadhali ^1ingia ndani^2 au ^3jisajili^4 ili kuliza swali.',
		'ask_same_q' => 'Kabla hujaendelea, tafadhali tazama endapo swali lako halijaulizwa:',
		'ask_title' => 'Uliza Swali',
		'c_notify_email' => 'Nitumie barua-pepe katika anuani hii endapo kuna maoni yatatolewa baada yangu:',
		'c_notify_label' => 'Nitumie barua-pepe endapo kuna maoni yatatolewa baada yangu',
		'c_notify_x_label' => 'Nitumie barua-pepe (^) endapo kuna maoni yatatolewa baada yangu',
		'c_waiting_your_approval' => 'Oni hili linasubiri uthibitisho wako',
		'c_your_waiting_approval' => 'Oni lako litatazamwa na kuthibitishwa hivi punde.',
		'category_ask_not_allowed' => 'Huna ruhusa ya kuuliza swali katika kategoria hii',
		'category_js_note' => 'Kuchagua kategoria yoyote, tafadhali wezesha Javascript katika kivinjari wavuti chako.',
		'category_required' => 'Tafadhali chagua kategoria',
		'claim_a_popup' => 'Idhinisha jibu hili katika akaunti yako',
		'claim_button' => 'Niliandika hili',
		'claim_c_popup' => 'Idhinisha oni hili katika akaunti yako',
		'claim_q_popup' => 'Idhinisha swali hili katika akaunti yako',
		'clear_flags_button' => 'futa bendera',
		'clear_flags_popup' => 'Ondoa bendera zilizowekwa na watumiajai wote',
		'close_button' => 'funga',
		'close_duplicate' => 'Swali hili ni nakala ya swali jingine',
		'close_duplicate_error' => 'Nakala hii ya swali haijaweza kupatikana - tafadhali jaribu kuingiza namba kutokea kwenye URL ya swali jingine, mfn. 123.',
		'close_form_button' => 'Funga swali',
		'close_form_title' => 'Funga swali hili',
		'close_original_note' => 'Waweza pia kuingiza namba ya swali katika URL, mfn. 123.',
		'close_original_title' => 'URL ya swali la kwanza:',
		'close_q_popup' => 'Funga swali hili kwa jibu lolote jipya',
		'close_reason_title' => 'Sababu ya kufunga swali hili:',
		'closed_as_duplicate' => 'limefungwa kwa kuwa ni nakala-pacha ya:',
		'closed_with_note' => 'limefungwa ikiwa na dondoo:',
		'comment_a_popup' => 'Ongeza oni katika swali hili',
		'comment_button' => 'maoni',
		'comment_limit' => 'Maoni mengi mno yamepokelewa - tafadhali jaribu tena baada ya saa moja',
		'comment_must_be_approved' => 'Akaunti yako lazima ithibitishwe kabla hujaongeza oni.',
		'comment_must_confirm' => 'Tafadhali ^5thibitihsa anuani yako ya barua-pepe^6 ili kuongeza oni.',
		'comment_must_login' => 'Tafadhali ^1ingia ndani^2 au ^3jisajili^4 ilinkuongeza oni.',
		'comment_on_a' => 'kwa jibu: ',
		'comment_on_q' => 'kwa swali: ',
		'comment_q_popup' => 'Ongeza oni katika swali hili',
		'delete_a_popup' => 'Futa hili jibu milele',
		'delete_button' => 'futa',
		'delete_c_popup' => 'Futa hili oni milele',
		'delete_q_popup' => 'Futa hili swali milele',
		'duplicate_content' => 'Jambo ulilotuma linaonekana kuwa ni marudio.',
		'edit_a_popup' => 'Hariri jibu hili',
		'edit_a_title' => 'Hariri Jibu',
		'edit_button' => 'hariri',
		'edit_c_popup' => 'Hariri hili oni',
		'edit_c_title' => 'Hariri oni',
		'edit_must_confirm' => 'Tafadhali ^5thibitihsa anuani yako ya barua-pepe^6 ili kuhariri.',
		'edit_must_login' => 'Tafadhali ^1ingia ndani^2 au ^3Jisajili^4 ili kuhariri.',
		'edit_q_popup' => 'Hariri swali hili',
		'edit_q_title' => 'Hariri swali',
		'example_tags' => 'Lebo za mfano: ',
		'flag_a_popup' => 'Liwekee bendera jibu hili kama barua-taka au lisilostahili',
		'flag_button' => 'weka bendera',
		'flag_c_popup' => 'Liwekee bendera oni hili kama oni-taka au lisilostahili',
		'flag_hide_button' => 'wekea bendera na lifiche',
		'flag_limit' => 'Machapisho mengi mno yamewekewa bendera - tafadhali jaribu tena baada ya saa moja',
		'flag_must_confirm' => 'Tafadhali ^5thibitisha anuani yako ya barua-pepe^6 ili kuwekea bendera chapisho.',
		'flag_must_login' => 'Tafadhali ^1ingia ndani^2 au ^3jisajili^4 ili kuwekea bendera chapisho.',
		'flag_not_allowed' => 'Kuweka bendera hili hairuhusiwi',
		'flag_q_popup' => 'Wekea bendera swali hili kama swali-taka au lisilokubalika',
		'follow_a_popup' => 'Uliza swali jipya linalohusiana na swali hili',
		'follow_button' => 'uliza swali linalofanana',
		'follows_a' => 'inahusiana na swali kwa:',
		'follows_q' => 'kuhusu swali:',
		'hide_a_popup' => 'Ficha jibu hili',
		'hide_button' => 'ficha',
		'hide_c_popup' => 'Ficha oni hili',
		'hide_q_popup' => 'Ficha swali hili',
		'matching_tags' => 'Oanisha lebo: ',
		'max_tags_x' => 'Kiwango cha juu kinachoruhusiwa  ni lebo ^',
		'min_tags_x' => 'Tafadhali weka walau lebo ^',
		'notify_email_note' => 'Faragha: Anuani yako ya barua-pepe itatumiwa katika kukutumia taarifa hizi tu.',
		'q_category_label' => 'Kategoria:',
		'q_content_label' => 'Maelezo zaidi kuhusu Swali hili:',
		'q_hidden_author' => 'Mtunzi wa swali hili amelificha',
		'q_hidden_flagged' => 'Swali hili limewekewa bendera na kufichwa',
		'q_hidden_other' => 'Swali hili limefichwa',
		'q_notify_email' => 'Nitumie barua-pepe kwa anuani hii endapo swali hili litajibiwa au kutolewa maoni katika:',
		'q_notify_label' => 'Nitumie barua-pepe endapo swali hili litajibiwa au kutolewa maoni katika',
		'q_notify_x_label' => 'Nitumie barua-pepe (^) endapo swali hili litajibiwa au kutolewa maoni katika',
		'q_tags_comma_label' => 'Lebo - tumia koma (,) kuzitenganisha:',
		'q_tags_label' => 'Lebo - tumia kistariungio (_) kuunganisha maneno:',
		'q_title_label' => 'Andika Swali Lako kwa Sentensi Moja:',
		'q_waiting_approval' => 'Swali hili linasubiri uthibitisho wako',
		'q_waiting_your_approval' => 'Swali hili linasubiri uthibitisho wako',
		'q_your_waiting_approval' => 'Swali lako litatazamwa na kuthibitishwa hivi punde.',
		'recat_button' => 'pangia upya kategoria',
		'recat_popup' => 'Badilisha kategoria ya swali hili',
		'recat_q_title' => 'Lipe swali kategoria mpya',
		'reject_a_popup' => 'Kataa jibu hili',
		'reject_button' => 'kataa',
		'reject_c_popup' => 'Kataa oni hili',
		'reject_q_popup' => 'Kataa swali hili',
		'remove_q_favorites' => 'Ondoa swali hili kutoka kwenye vipendeleo vyangu',
		'reopen_button' => 'fungua upya',
		'reopen_q_popup' => 'Fungua upya swali hili',
		'reply_button' => 'jibu',
		'reply_c_popup' => 'jibu oni hili',
		'reshow_a_popup' => 'Onesha upya jibu hili',
		'reshow_button' => 'onesha upya',
		'reshow_c_popup' => 'Onesha upya one hili',
		'reshow_q_popup' => 'Onesha upya swali hili',
		'retag_button' => 'weka lebo upya',
		'retag_cat_popup' => 'Badili kategoria au lebo ya swali hili',
		'retag_popup' => 'Badili lebo ya swali hili',
		'retag_q_title' => 'Weka upya lebo ya swali',
		'save_silent_label' => 'Hifadhi kimyakimya kuficha ya kwamba swali hili limehaririwa',
		'select_popup' => 'Bofya kulichagua kama jibu bora zaidi',
		'select_text' => 'Jibu Bora Zaidi',
		'show_1_comment' => 'Onesha oni 1',
		'show_1_previous_comment' => 'Onesha one 1 lililopita',
		'show_x_comments' => 'Onesha Maoni ^',
		'show_x_previous_comments' => 'Onesha Maoni ^ yaliyopita',
		'unflag_button' => 'ondoa bendera',
		'unflag_popup' => 'Ondoa bendera uliyoiongeza',
		'unselect_popup' => 'Bofya kuondoa chaguo',
		'x_answers_title' => 'Majibu ^',
		'your_answer_title' => 'Jibu lako',
		'your_comment_a' => 'Oni lako katika jibu hili:',
		'your_comment_q' => 'Oni lako katika swali hili:',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
