<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-main.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => 'jibu 1',
		'1_comment' => 'maoni 1',
		'1_day' => 'siku 1',
		'1_disliked' => 'kutopendwa 1',
		'1_flag' => 'alama 1',
		'1_hour' => 'saa 1',
		'1_liked' => 'Kupendwa 1',
		'1_minute' => 'dakika 1',
		'1_month' => 'mwezi 1',
		'1_point' => 'pointi 1',
		'1_question' => 'swali 1',
		'1_second' => 'yapili 1',
		'1_tag' => 'lebo 1',
		'1_user' => 'mtumiaji 1',
		'1_view' => 'Onwa 1',
		'1_vote' => 'Kura 1',
		'1_week' => 'wiki 1',
		'1_year' => 'mwaka 1',
		'add_category_x_favorites' => 'Ongeza Kategoria ^ katika orodha ya vipendwa vyangu',
		'add_favorites' => 'Ongeza katika orodha ya vipendwa vyangu',
		'add_tag_x_favorites' => 'Ongeza lebo ^ katika orodha ya vipendwa vyangu',
		'all_categories' => 'Kategoria zote',
		'anonymous' => 'bilajina',
		'answer_edited' => 'jibu limehaririwa',
		'answer_reshown' => 'jibu limeoneshwa tena',
		'answer_selected' => 'jibu limechaguliwa',
		'answered' => 'limejibiwa',
		'answered_qs_in_x' => 'Swali lililojibiwa mara nyingi zaidi^',
		'answered_qs_title' => 'Maswali yaliyojibiwa mara nyingi zaidi',
		'asked' => 'limeulizwa',
		'asked_related_q' => 'uliulizwa swalia lifananalo',
		'by_x' => 'na ^',
		'cancel_button' => 'acha',
		'closed' => 'funga',
		'comment_edited' => 'maoni yamehaririwa',
		'comment_moved' => 'maoni yameondolewa',
		'comment_reshown' => 'maoni yameoneshwa tena',
		'commented' => 'imewekwa maoni',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^month ^day, ^year',
		'date_format_this_year' => '^month ^day',
		'date_month_1' => 'Jan',
		'date_month_2' => 'Feb',
		'date_month_3' => 'Mar',
		'date_month_4' => 'Apr',
		'date_month_5' => 'May',
		'date_month_6' => 'Jun',
		'date_month_7' => 'Jul',
		'date_month_8' => 'Aug',
		'date_month_9' => 'Sep',
		'date_month_10' => 'Oct',
		'date_month_11' => 'Nov',
		'date_month_12' => 'Dec',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'imehaririwa',
		'email_error' => 'Kosa limetokea wakati wa kujaribu kutuma barua-pepe.',
		'field_required' => 'Tafadhali andika kitu katika nafasi hii',
		'file_upload_limit_exceeded' => 'Ukubwa wa faili umezidi kiwango cha juu cha kuhifadhiwa na Seva',
		'general_error' => 'Kasoro imetokea kwa Seva - tafadhali jaribu tena.',
		'hidden' => 'imefichwa',
		'highest_users' => 'Mtumiaji aliyepata alama nyingi zaidi',
		'hot_qs_in_x' => 'Swali motomoto katika ^',
		'hot_qs_title' => 'Swali motomoto',
		'image_not_read' => 'Picha haikuwezwa kusomwa. Tafadhali pakia moja ya: ^',
		'image_too_big_x_pc' => 'Picha hii ni kubwa mno. Tafadhali irekebisha kuwa ^% halafu ujaribu tena.',
		'in_category_x' => 'katika ^',
		'ip_address_x' => 'Anuani ya IP ^',
		'logged_in_x' => 'Halo ^',
		'max_length_x' => 'Urefu wa juu sentensi ni herufi ^',
		'max_upload_size_x' => 'Ukubwa wa juu kabisa wa kupakia ni ^',
		'me' => 'mimi',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Tafadhali ongeza maelezo zaidi - ngaa herufi ^ ',
		'moved' => 'imetolewa',
		'nav_activity' => 'Shughuli zote',
		'nav_admin' => 'Msimamizi',
		'nav_ask' => 'Uliza Swali',
		'nav_categories' => 'Kategoria',
		'nav_feedback' => 'Tuma Mrejesho',
		'nav_home' => 'Nyumbani',
		'nav_hot' => 'Motomoto!',
		'nav_login' => 'Ingia',
		'nav_logout' => 'Toka',
		'nav_most_answers' => 'Majibu mengi',
		'nav_most_recent' => 'Ya hivi punde',
		'nav_most_views' => 'Yaliyotazamwa mno',
		'nav_most_votes' => 'Yenye kura nyingi',
		'nav_no_answer' => 'Hakuna jibu',
		'nav_no_selected_answer' => 'Hakuna jibu lililochaguliwa',
		'nav_no_upvoted_answer' => 'Hakuna jibu lililopigiwa kura',
		'nav_qa' => 'Q&A',
		'nav_qs' => 'Maswali',
		'nav_register' => 'Andikisha',
		'nav_tags' => 'Lebo',
		'nav_unanswered' => 'Yasiyojibiwa',
		'nav_updates' => 'Maboresho Yangu',
		'nav_users' => 'Watumiaji',
		'no_active_users' => 'Hakujapatikana watumiaji amilifu',
		'no_answers_found' => 'Jakujapatikana Jibu',
		'no_answers_in_x' => 'Hakuna Jibu katika ^',
		'no_categories_found' => 'Hakujapatikana Kategoria',
		'no_category' => 'Hakuna Kategoria',
		'no_comments_found' => 'Hakujapatikana Maoni',
		'no_comments_in_x' => 'Hakuna Maoni katika ^',
		'no_questions_found' => 'Hakujapatikana Swali',
		'no_questions_in_x' => 'Hakujapatikana Swali katika ^',
		'no_related_qs_title' => 'Hakujapatikana Swali linalofanana',
		'no_results_for_x' => 'Hakujapatikana jibu kwa ^',
		'no_tags_found' => 'Hakujapatikana Lebo',
		'no_una_questions_found' => 'Hakujapatikana Swali ambalo halijajibiwa',
		'no_una_questions_in_x' => 'Hakuna Swali Lisilojibiwa katika ^',
		'no_unselected_qs_found' => 'Hakujapatikana Swali Ambalo Halijachaguliwa Jibu',
		'no_unupvoteda_qs_found' => 'Hakujapatikana Swali bila jibu lililopigiwa kura',
		'page_label' => 'Ukurasa:',
		'page_next' => 'ufuatayo',
		'page_not_found' => 'Ukurasa Haujapatikana',
		'page_prev' => 'uliopita',
		'popular_tags' => 'Lebo Maarufu Zaidi',
		'questions_tagged_x' => 'Recent questions tagged Maswali ya Hivi Karibuni Yenye Lebo ^',
		'recategorized' => 'Weka Kategoria Upya',
		'recent_activity_in_x' => 'Shughuli za hivi karibuni katika ^',
		'recent_activity_title' => 'Shughuli za Hivi karibuni',
		'recent_as_in_x' => 'Maswali Yaliyojibiwa hivi karibuni katika ^',
		'recent_as_title' => 'Maswali Yaliyojibiwa hivi karibuni',
		'recent_cs_in_x' => 'Maswali Yaliyotolewa Maoni hivi Karibuni katika ^',
		'recent_cs_title' => 'Maswali yaliyotolewa Maoni hivi karibuni',
		'recent_qs_as_in_x' => 'Maswali na Majibu ya Hivi karibuni katika ^',
		'recent_qs_as_title' => 'Maswali na Majibu ya hivi karibuni',
		'recent_qs_in_x' => 'Maswali ya hivi karibuni katika ^',
		'recent_qs_title' => 'Maswali ya Hivi karibuni',
		'related_qs_title' => 'Maswali Yafananayo',
		'remove_favorites' => 'Ondoa Katika Vipendeleo vyangu',
		'remove_x_favorites' => 'Ondoa ^ Kutoka kwa Vipendenleo Vyangu',
		'reopened' => 'Fungua Upya',
		'reshown' => 'Onesha Upya',
		'results_for_x' => 'Tafuta Majibu ya ^',
		'retagged' => 'Weka Lebo Upya',
		'save_button' => 'Hifadhi Mabadiliko',
		'search_button' => 'Tafuta',
		'search_explanation' => 'Tafadhali andika maneno katika kisanduka cha kutafuta, na kisha ujaribu tena.',
		'search_title' => 'Matokeo Yaliyopatikana',
		'selected' => 'ilochaguliwa',
		'send_button' => 'Tuma',
		'since_x' => 'tangu ^',
		'suggest_ask' => 'Wezesha vitu kuanza kwa  ^1kuuliza Swali^2.',
		'suggest_category_qs' => 'Ili kuona Zaidi, bofya Maswali yote ^1katika kategoria hii^2.',
		'suggest_qs' => 'Kuona zaidi, bofya kwa ^1orodha ya maswali yote^2.',
		'suggest_qs_tags' => 'Kuona Zaidi, bofya kwa orodha ^1yote ya maswali^2 au ^3lebo mashuhuri^4.',
		'to_x' => 'kwa ^',
		'unanswered_qs_in_x' => 'Maswali yasiyo na Majibu katika ^',
		'unanswered_qs_title' => 'Mswali ya hivi karibuni yasiyo na Majibu',
		'unselected_qs_in_x' => 'Maswali ambayo hayajachaguliwa majibu katika ^',
		'unselected_qs_title' => 'Maswali ya hivi karibuni ambayo hayajachaguliwa majibu',
		'unupvoteda_qs_in_x' => 'Maswali yasiyo na Majibu ambayo hayajapigiwa kura katika ^',
		'unupvoteda_qs_title' => 'Maswali ya hivi karibuni yasiyo na jibu lililopigiwa kura',
		'upload_limit' => 'Umepakia Mno - tafadhali jaribu tena baada ya saa moja',
		'view_q_must_be_approved' => 'Akaunti yako lazima ithibitishwe ili kuona kurasa za maswali.',
		'view_q_must_confirm' => 'Tafadhali ^5thibitisha barua-pepe yako^6 ili kuona kurasa za maswali.',
		'view_q_must_login' => 'Tafadhali ^1Ingia ndani^2 au ^3Jisajili^4 ili kuona kurasa za maswali.',
		'viewed_qs_in_x' => 'Maswali yaliyosomwa zaidi katika ^',
		'viewed_qs_title' => 'Maswali yaliyosomwa zaidi',
		'vote_disabled_approve' => 'Akaunti yako lazima ithibitishwe kabla ya kuweza kupiga kura',
		'vote_disabled_down' => 'Upigaji kura ya Hapana kunawezekana kwa baadhi ya watumiaji tu',
		'vote_disabled_down_approve' => 'Akaunti yako lazima ithibitishwe kabla ya kuweza kupiga kura ya hapana',
		'vote_disabled_hidden_a' => 'Huwezi kupigia kura majibu yaliyofichwa',
		'vote_disabled_hidden_q' => 'Huwezi kupigia Kura maswali yaliyofichwa',
		'vote_disabled_level' => 'Upigaji kura kunawezekana kwa baadhi ya watumiaji tu',
		'vote_disabled_my_a' => 'Huwezi kupigia kura jibu lako mwenyewe',
		'vote_disabled_my_q' => 'Huwezi kupigia kura swali lako mwenyewe',
		'vote_disabled_q_page_only' => 'Tafadhali soma hili swali ili uwezi kulipigia kura',
		'vote_down_must_confirm' => 'Tafadhali ^5thibitisha anuani yako ya barua-pepe^6 ili kuweza kupiga kura ya hapana.',
		'vote_down_popup' => 'Bofya hapa kupiga kura ya hapana',
		'vote_limit' => 'Kura nyingi mno zimeshapokelewa - tafadhali jaribu tena baada ya saa moja',
		'vote_must_confirm' => 'Tafadhali ^5thibitihsa anuani ya barua-pepe yako^6 ili kupiga kura.',
		'vote_must_login' => 'Tafadhali ^1Ingia ndani^2 au ^3jisajili^4 ili kupiga kura.',
		'vote_not_allowed' => 'Kupigia kura hili haliwezekani',
		'vote_up_popup' => 'Bofya kupiga kura ya ndio',
		'voted_down_popup' => 'You have voted this down - click to remove vote',
		'voted_qs_in_x' => 'Swali lililopigiwa kura zaidi katika ^',
		'voted_qs_title' => 'Swali lililopigiwa kura zaidi',
		'voted_up_popup' => 'Umelipigia kura ya ndio - bofya kuondoa kura yako',
		'written' => '', // blank in English - placeholder for other languages
		'x_ago' => '^ iliyopita',
		'x_answers' => 'majibu ^',
		'x_comments' => 'maoni ^',
		'x_days' => 'siku ^',
		'x_disliked' => 'Kutopenda ^',
		'x_flags' => 'alama ^',
		'x_hours' => 'saa ^',
		'x_liked' => 'Penda ^',
		'x_minutes' => 'dakika ^',
		'x_months' => 'miezi ^',
		'x_points' => ' pointi ^',
		'x_questions' => 'maswali ^',
		'x_seconds' => 'sekunde ^',
		'x_tags' => 'lebo ^',
		'x_users' => 'watumiaji ^',
		'x_views' => 'Mitazamo ^',
		'x_votes' => 'Kura ^',
		'x_weeks' => 'wiki ^',
		'x_years' => 'miaka ^',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/